local icons = {
  apple = "",
  cpu   = "",
  disk  = "󰋊",
  memory = "",
  volume = { _100 = "", _66 = "", _33 = "", _10 = "", _0  = "" },
  battery = { _100 = "", _75  = "", _50 = "", _25 = "", _0  = "", charging = "" },
  wifi  = { connected = "󰖩", disconnected = "󰖪" },
  media = { back = "", forward = "", play = "", pause = "" },
  spaces = { default = "", active = "", occupied = "" },
  app = {
    ["Finder"]   = "󰀶",
    ["Ghostty"]  = "",
    ["Terminal"] = "",
    ["Safari"]   = "󰀹",
    ["Google Chrome"] = "",
    ["Firefox"]  = "",
    ["Arc"]      = "",
    ["Code"]     = "",
    ["Slack"]    = "󰒱",
    ["Spotify"]  = "",
    ["Discord"]  = "󰙯",
    ["Messages"] = "󰍡",
    ["Mail"]     = "󰇮",
    ["Notes"]    = "󰏖",
    ["Calendar"] = "",
    ["Photos"]   = "󰄖",
    ["Music"]    = "",
    ["Preview"]  = "󰋲",
    ["Helium"]   = "",
    ["OrbStack"] = "󰡨",
    ["System Settings"] = "",
  },
  calendar = "",
  clock    = "",
  weather  = "",
  bluetooth = "",
}

return icons
